<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateMsFormFieldTable extends Migration
{
    /**
     * Supported field types:
     *   short_text, long_text, email, number, phone,
     *   date, time, datetime,
     *   dropdown, radio, checkbox,
     *   file, image,
     *   section_break, paragraph (display-only),
     *   rating, signature (future)
     */
    public function up(): void
    {
        if (Schema::hasTable('ms_form_field')) {
            return;
        }

        Schema::create('ms_form_field', function (Blueprint $table) {
            $table->bigIncrements('formFieldID');
            $table->unsignedBigInteger('formID')->index();
            $table->unsignedBigInteger('formSectionID')->nullable()->index();

            // Field definition
            $table->string('fieldType', 50)->index()->comment('short_text, email, dropdown, file, etc.');
            $table->string('label', 500)->comment('Question / field label shown to user');
            $table->string('placeholder', 255)->nullable();
            $table->string('helpText', 500)->nullable()->comment('Helper text displayed below the field');

            // Behaviour
            $table->boolean('isRequired')->default(false);
            $table->boolean('isSystemField')->default(false)
                  ->comment('1 = auto-generated by system, cannot be deleted by admin (e.g. mandatory email field)');

            // Display order
            $table->unsignedInteger('sortOrder')->default(0)->index();

            // Typed configuration stored as JSON
            $table->json('options')->nullable()
                  ->comment('For dropdown/radio/checkbox: [{label, value, isDefault}]');
            $table->json('validation')->nullable()
                  ->comment('Validation rules: {min, max, pattern, acceptedTypes, maxSizeKB}');
            $table->text('defaultValue')->nullable();
            $table->json('conditionalLogic')->nullable()
                  ->comment('Show/hide logic: {action, conditions: [{fieldID, operator, value}]}');
            $table->json('fieldConfig')->nullable()
                  ->comment('Extra config: {gdriveFolderID, gdriveAttachmentsFolderUrl, columnWidth, etc.}');

            // Soft delete (keep for historical submission integrity)
            $table->boolean('flagActive')->default(true)->index();
            $table->dateTime('createdDate');
            $table->dateTime('editedDate')->nullable();

            $table->foreign('formID')
                  ->references('formID')
                  ->on('ms_form')
                  ->onDelete('cascade');

            $table->foreign('formSectionID')
                  ->references('formSectionID')
                  ->on('ms_form_section')
                  ->onDelete('set null');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ms_form_field');
    }
}
