<?php

return [
    'list' => [
        'Akuntan',
        'Admin',
        'AI Researcher',
        'Air Traffic Controller',
        'Animal Trainer',
        'Animator',
        'Archaeologist',
        'Arsitek',
        'Art Therapist',
        'Astrophysicist',
        'Astronomer',
        'Automotive Mechanic',
        'Bendahara',
        'Bidan',
        'Bioinformatician',
        'Blockchain Developer',
        'Brand Manager',
        'Cartoonist',
        'Chemical Engineer',
        'Chief Creative Officer',
        'Chief Data Officer',
        'Chief Diversity Officer',
        'Chief Executive Officer',
        'Chief Financial Officer',
        'Chief Human Resources Officer',
        'Chief Marketing Officer',
        'Chief Operating Officer',
        'Chief Sustainability Officer',
        'Chief Technology Officer',
        'Chiropractor',
        'Civil Engineer',
        'Climate Change Analyst',
        'Clinical Psychologist',
        'Content Creator',
        'Consultant',
        'Cryptocurrency Trader',
        'Cybersecurity Analyst',
        'Data Analyst',
        'Data Scientist',
        'Dentist',
        'Desainer',
        'Dokter',
        'Dosen',
        'Environmental Engineer',
        'Environmental Scientist',
        'Ethnographer',
        'Ethical Hacker',
        'Event Coordinator',
        'Event Planner',
        'Fashion Designer',
        'Fashion Stylist',
        'Film Director',
        'Financial Advisor',
        'Fitness Trainer',
        'Flight Attendant',
        'Food Scientist',
        'Forensic Scientist',
        'Futurist',
        'Game Developer',
        'Geologist',
        'Geophysicist',
        'Guru',
        'Guru Les',
        'Historian',
        'Horticulturist',
        'HR Specialist',
        'Interior Decorator',
        'Interior Designer',
        'Investment Banker',
        'Karyawan',
        'Karyawan Bank',
        'Koki',
        'Konsultan',
        'Loan Officer',
        'Mahasiswa',
        'Manajer',
        'Marine Biologist',
        'Marketing',
        'Media Buyer',
        'Meteorologist',
        'Montir',
        'Motivational Speaker',
        'Museum Curator',
        'Nelayan',
        'Neonatal Nurse',
        'Neuroscientist',
        'Nurse Anesthetist',
        'Nutritionist',
        'Park Ranger',
        'Pedagang',
        'Pemadam Kebakaran',
        'Pemandu Wisata',
        'Pemilik Toko',
        'Penjaga Toko',
        'Peneliti',
        'Penyanyi',
        'Penulis',
        'Personal Chef',
        'Petani',
        'Peternak',
        'Petugas Kebersihan',
        'Pekerja Konstruksi',
        'Photographer',
        'Physical Education Teacher',
        'Physical Therapist',
        'Pilot',
        'Podcaster',
        'Podiatrist',
        'Polisi',
        'Political Analyst',
        'PNS',
        'Pramugara',
        'Pramugari',
        'Programmer',
        'Public Relations Specialist',
        'Quality Assurance',
        'Quality Control',
        'Robotics Engineer',
        'Satpam',
        'Sekretaris',
        'Seniman',
        'Social Worker',
        'Sociologist',
        'Software Engineer',
        'Sopir',
        'Sound Designer',
        'Speech Language Pathologist',
        'Speech Therapist',
        'Suster',
        'Technical Writer',
        'TNI',
        'Translator',
        'Travel Blogger',
        'Tukang Besi',
        'Tukang Cukur',
        'Tukang Jahit',
        'Tukang Kayu',
        'Tukang Las',
        'Tukang Listrik',
        'Urban Planner',
        'User Experience Designer',
        'Voice Actor',
        'Wildlife Biologist',
        'Wirausaha',
        'Yoga Instructor',
        'Zoologist',
        'Lainnya',
    ],
];
